#!/bin/bash

# ----------------------------------
# Colors
# ----------------------------------
NC='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'

sleep 1
echo "-------------------------------------"
echo "        Jetbackup Installer          "
echo "Author: Ankesh Anand                 "
echo "Copyright: GNU General Public License"
echo "Supported: cPanel                    "
echo "Version: 1.0.0                       "
echo "Release Date: 06/11/2021             "
echo "-------------------------------------"
sleep 1
echo ""

echo "Installation would start in 10sec. To Cancel Installation,Click Ctrl+C"
sleep 10

echo -e "${YELLOW}Installing Repo${NC}"
sleep 1
yum install -y http://repo.jetlicense.com/centOS/jetapps-repo-latest.rpm > /etc/jetbackup_install.log
yum clean all --enablerepo=jetapps* > /etc/jetbackup_install.log

echo -e "${YELLOW}Installing Jetapps cPanel Plugin${NC}"
sleep 1
yum install -y jetapps-cpanel --disablerepo=* --enablerepo=jetapps > /etc/jetbackup_install.log

echo -e "${YELLOW}Installing JetBackup Stable release${NC}"
sleep 1
jetapps --install jetbackup stable > /etc/jetbackup_install.log

if rpm -q --quiet jetbackup ; then
	echo -e "${GREEN}Jetbackup Installed successfully${NC}"
	echo -e "${YELLOW}Do you want to delete the Installation log file?(Y/N) ${NC}"
	read DELT
	if [[ "$DELT" == "Y" || "$DELT" == "y" ]]; then
	rm -rf /etc/jetbackup_install.log > /dev/null
	else
	echo -e "${GREEN}Goodbye!${NC}"
	fi
else
	echo -e "${RED}Installation failed, please check logs${NC}"
	echo -e "${RED}/etc/jetbackup_install.log ${NC}"
	echo -e "${RED}Goodbye!${NC}"
fi
